// This file is auto-generated by @hey-api/openapi-ts

export const AnalysisStatusSchema = {
    type: 'string',
    enum: ['PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'],
    title: 'AnalysisStatus',
    description: 'Image analysis task status.'
} as const;

export const Body_llm_prompts_test_llm_promptSchema = {
    properties: {
        llm_model_config_id: {
            type: 'integer',
            title: 'Llm Model Config Id'
        },
        image: {
            type: 'string',
            format: 'binary',
            title: 'Image'
        }
    },
    type: 'object',
    required: ['llm_model_config_id', 'image'],
    title: 'Body_llm-prompts-test_llm_prompt'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ImageAnalysesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ImageAnalysisPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ImageAnalysesPublic',
    description: 'List of Image Analyses.'
} as const;

export const ImageAnalysisPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        img_path: {
            type: 'string',
            title: 'Img Path'
        },
        source_type: {
            '$ref': '#/components/schemas/ImageSourceType'
        },
        llm_prompt_id: {
            type: 'integer',
            title: 'Llm Prompt Id'
        },
        model_name: {
            type: 'string',
            title: 'Model Name'
        },
        status: {
            '$ref': '#/components/schemas/AnalysisStatus'
        },
        analysis_result: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Analysis Result'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'img_path', 'source_type', 'llm_prompt_id', 'model_name', 'status', 'created_at', 'updated_at'],
    title: 'ImageAnalysisPublic',
    description: 'Public schema for Image Analysis (API response).'
} as const;

export const ImageSourceTypeSchema = {
    type: 'string',
    enum: ['SIYUAN_LOCAL', 'URL'],
    title: 'ImageSourceType'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const LLMModelConfigCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name',
            description: 'Configuration name'
        },
        provider: {
            '$ref': '#/components/schemas/LLMProvider',
            description: 'Model provider type'
        },
        model_id: {
            type: 'string',
            title: 'Model Id',
            description: 'Model ID/name'
        },
        base_url: {
            type: 'string',
            title: 'Base Url',
            description: 'API base URL'
        },
        config: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Config',
            description: 'Additional configuration'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            description: 'Whether config is active',
            default: true
        },
        api_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Key',
            description: 'API key'
        }
    },
    type: 'object',
    required: ['name', 'provider', 'model_id', 'base_url'],
    title: 'LLMModelConfigCreate',
    description: 'Schema for creating LLM Model Config.'
} as const;

export const LLMModelConfigPublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name',
            description: 'Configuration name'
        },
        provider: {
            '$ref': '#/components/schemas/LLMProvider',
            description: 'Model provider type'
        },
        model_id: {
            type: 'string',
            title: 'Model Id',
            description: 'Model ID/name'
        },
        base_url: {
            type: 'string',
            title: 'Base Url',
            description: 'API base URL'
        },
        config: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Config',
            description: 'Additional configuration'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            description: 'Whether config is active',
            default: true
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'provider', 'model_id', 'base_url', 'id'],
    title: 'LLMModelConfigPublic',
    description: 'Public schema for LLM Model Config (API response).'
} as const;

export const LLMModelConfigUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        provider: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/LLMProvider'
                },
                {
                    type: 'null'
                }
            ]
        },
        model_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Model Id'
        },
        base_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Url'
        },
        api_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Api Key'
        },
        config: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Config'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'LLMModelConfigUpdate',
    description: 'Schema for updating LLM Model Config.'
} as const;

export const LLMModelConfigsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/LLMModelConfigPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'LLMModelConfigsPublic',
    description: 'List of LLM Model Configs.'
} as const;

export const LLMPromptCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name',
            description: 'Prompt template name'
        },
        content: {
            type: 'string',
            title: 'Content',
            description: 'Prompt template content'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            description: 'Whether prompt is active',
            default: true
        }
    },
    type: 'object',
    required: ['name', 'content'],
    title: 'LLMPromptCreate',
    description: 'Schema for creating LLM Prompt.'
} as const;

export const LLMPromptPublicSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name',
            description: 'Prompt template name'
        },
        content: {
            type: 'string',
            title: 'Content',
            description: 'Prompt template content'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            description: 'Whether prompt is active',
            default: true
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'content', 'id'],
    title: 'LLMPromptPublic',
    description: 'Public schema for LLM Prompt (API response).'
} as const;

export const LLMPromptTestResponseSchema = {
    properties: {
        result: {
            type: 'string',
            title: 'Result',
            description: 'Analysis result from LLM'
        }
    },
    type: 'object',
    required: ['result'],
    title: 'LLMPromptTestResponse',
    description: 'Response schema for LLM Prompt test.'
} as const;

export const LLMPromptUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'LLMPromptUpdate',
    description: 'Schema for updating LLM Prompt.'
} as const;

export const LLMPromptsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/LLMPromptPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'LLMPromptsPublic',
    description: 'List of LLM Prompts.'
} as const;

export const LLMProviderSchema = {
    type: 'string',
    enum: ['OPENAI', 'ANTHROPIC', 'OLLAMA'],
    title: 'LLMProvider',
    description: `LLM/LLM model provider types.

Note: All providers are accessed through agno framework as unified agent interface.
The provider type indicates which underlying model service to use, but all calls
go through agno Agent for consistency.`
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const SourceConfigCreateSchema = {
    properties: {
        type: {
            '$ref': '#/components/schemas/SourceType',
            description: 'Data source type'
        },
        name: {
            type: 'string',
            title: 'Name',
            description: 'User-defined name for this configuration'
        },
        config_payload: {
            additionalProperties: true,
            type: 'object',
            title: 'Config Payload',
            description: 'Source-specific configuration'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            description: 'Whether this config is active',
            default: true
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        }
    },
    type: 'object',
    required: ['type', 'name', 'config_payload', 'user_id'],
    title: 'SourceConfigCreate',
    description: 'Schema for creating a new source configuration.'
} as const;

export const SourceConfigPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        type: {
            '$ref': '#/components/schemas/SourceType',
            description: 'Data source type'
        },
        name: {
            type: 'string',
            title: 'Name',
            description: 'User-defined name for this configuration'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            description: 'Whether this config is active',
            default: true
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'type', 'name', 'created_at', 'updated_at'],
    title: 'SourceConfigPublic',
    description: 'Schema for source configuration returned from API.'
} as const;

export const SourceConfigUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        config_payload: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Config Payload'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'SourceConfigUpdate',
    description: 'Schema for updating source configuration.'
} as const;

export const SourceConfigsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SourceConfigPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SourceConfigsPublic',
    description: 'Schema for paginated list of source configurations.'
} as const;

export const SourceTypeSchema = {
    type: 'string',
    enum: ['GIT', 'DAYFLOW', 'SIYUAN'],
    title: 'SourceType',
    description: 'Data source types.'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;