// This file is auto-generated by @hey-api/openapi-ts

/**
 * Image analysis task status.
 */
export type AnalysisStatus = 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'FAILED';

export type Body_llm_prompts_test_llm_prompt = {
    llm_model_config_id: number;
    image: (Blob | File);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * List of Image Analyses.
 */
export type ImageAnalysesPublic = {
    data: Array<ImageAnalysisPublic>;
    count: number;
};

/**
 * Public schema for Image Analysis (API response).
 */
export type ImageAnalysisPublic = {
    id: number;
    img_path: string;
    source_type: ImageSourceType;
    llm_prompt_id: number;
    model_name: string;
    status: AnalysisStatus;
    analysis_result?: (string | null);
    error_message?: (string | null);
    created_at: string;
    updated_at: string;
};

export type ImageSourceType = 'SIYUAN_LOCAL' | 'URL';

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

/**
 * Schema for creating LLM Model Config.
 */
export type LLMModelConfigCreate = {
    /**
     * Configuration name
     */
    name: string;
    /**
     * Model provider type
     */
    provider: LLMProvider;
    /**
     * Model ID/name
     */
    model_id: string;
    /**
     * API base URL
     */
    base_url: string;
    /**
     * Additional configuration
     */
    config?: ({
    [key: string]: unknown;
} | null);
    /**
     * Whether config is active
     */
    is_active?: boolean;
    /**
     * API key
     */
    api_key?: (string | null);
};

/**
 * Public schema for LLM Model Config (API response).
 */
export type LLMModelConfigPublic = {
    /**
     * Configuration name
     */
    name: string;
    /**
     * Model provider type
     */
    provider: LLMProvider;
    /**
     * Model ID/name
     */
    model_id: string;
    /**
     * API base URL
     */
    base_url: string;
    /**
     * Additional configuration
     */
    config?: ({
    [key: string]: unknown;
} | null);
    /**
     * Whether config is active
     */
    is_active?: boolean;
    id: number;
};

/**
 * List of LLM Model Configs.
 */
export type LLMModelConfigsPublic = {
    data: Array<LLMModelConfigPublic>;
    count: number;
};

/**
 * Schema for updating LLM Model Config.
 */
export type LLMModelConfigUpdate = {
    name?: (string | null);
    provider?: (LLMProvider | null);
    model_id?: (string | null);
    base_url?: (string | null);
    api_key?: (string | null);
    config?: ({
    [key: string]: unknown;
} | null);
    is_active?: (boolean | null);
};

/**
 * Schema for creating LLM Prompt.
 */
export type LLMPromptCreate = {
    /**
     * Prompt template name
     */
    name: string;
    /**
     * Prompt template content
     */
    content: string;
    /**
     * Whether prompt is active
     */
    is_active?: boolean;
};

/**
 * Public schema for LLM Prompt (API response).
 */
export type LLMPromptPublic = {
    /**
     * Prompt template name
     */
    name: string;
    /**
     * Prompt template content
     */
    content: string;
    /**
     * Whether prompt is active
     */
    is_active?: boolean;
    id: number;
};

/**
 * List of LLM Prompts.
 */
export type LLMPromptsPublic = {
    data: Array<LLMPromptPublic>;
    count: number;
};

/**
 * Response schema for LLM Prompt test.
 */
export type LLMPromptTestResponse = {
    /**
     * Analysis result from LLM
     */
    result: string;
};

/**
 * Schema for updating LLM Prompt.
 */
export type LLMPromptUpdate = {
    name?: (string | null);
    content?: (string | null);
    is_active?: (boolean | null);
};

/**
 * LLM/LLM model provider types.
 *
 * Note: All providers are accessed through agno framework as unified agent interface.
 * The provider type indicates which underlying model service to use, but all calls
 * go through agno Agent for consistency.
 */
export type LLMProvider = 'OPENAI' | 'ANTHROPIC' | 'OLLAMA';

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Request body for SiYuan SQL execution.
 */
export type SiYuanSQLRequest = {
    stmt: string;
};

/**
 * Response for SiYuan SQL execution.
 */
export type SiYuanSQLResponse = {
    success: boolean;
    data?: (Array<{
    [key: string]: unknown;
}> | null);
    error?: (string | null);
};

/**
 * Schema for creating a new source configuration.
 */
export type SourceConfigCreate = {
    /**
     * Data source type
     */
    type: SourceType;
    /**
     * User-defined name for this configuration
     */
    name: string;
    /**
     * Source-specific configuration
     */
    config_payload: {
        [key: string]: unknown;
    };
    /**
     * Whether this config is active
     */
    is_active?: boolean;
    user_id: string;
};

/**
 * Schema for source configuration returned from API.
 */
export type SourceConfigPublic = {
    id: number;
    user_id: string;
    /**
     * Data source type
     */
    type: SourceType;
    /**
     * User-defined name for this configuration
     */
    name: string;
    /**
     * Whether this config is active
     */
    is_active?: boolean;
    created_at: string;
    updated_at: string;
};

/**
 * Schema for paginated list of source configurations.
 */
export type SourceConfigsPublic = {
    data: Array<SourceConfigPublic>;
    count: number;
};

/**
 * Schema for updating source configuration.
 */
export type SourceConfigUpdate = {
    name?: (string | null);
    config_payload?: ({
    [key: string]: unknown;
} | null);
    is_active?: (boolean | null);
};

/**
 * Data source types.
 */
export type SourceType = 'GIT' | 'DAYFLOW' | 'SIYUAN';

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type DebugExecuteSiyuanSqlData = {
    requestBody: SiYuanSQLRequest;
};

export type DebugExecuteSiyuanSqlResponse = (SiYuanSQLResponse);

export type HealthHealthResponse = (unknown);

export type ImageAnalysesReadImageAnalysesData = {
    limit?: number;
    skip?: number;
    /**
     * Filter by analysis status
     */
    status?: (AnalysisStatus | null);
};

export type ImageAnalysesReadImageAnalysesResponse = (ImageAnalysesPublic);

export type ImageAnalysesReadImageAnalysisData = {
    id: number;
};

export type ImageAnalysesReadImageAnalysisResponse = (ImageAnalysisPublic);

export type ImageAnalysesGetImageAnalysisImageData = {
    id: number;
};

export type ImageAnalysesGetImageAnalysisImageResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LlmModelConfigsReadLlmModelConfigsData = {
    limit?: number;
    skip?: number;
};

export type LlmModelConfigsReadLlmModelConfigsResponse = (LLMModelConfigsPublic);

export type LlmModelConfigsCreateLlmModelConfigData = {
    requestBody: LLMModelConfigCreate;
};

export type LlmModelConfigsCreateLlmModelConfigResponse = (LLMModelConfigPublic);

export type LlmModelConfigsReadLlmModelConfigData = {
    id: number;
};

export type LlmModelConfigsReadLlmModelConfigResponse = (LLMModelConfigPublic);

export type LlmModelConfigsUpdateLlmModelConfigData = {
    id: number;
    requestBody: LLMModelConfigUpdate;
};

export type LlmModelConfigsUpdateLlmModelConfigResponse = (LLMModelConfigPublic);

export type LlmModelConfigsDeleteLlmModelConfigData = {
    id: number;
};

export type LlmModelConfigsDeleteLlmModelConfigResponse = (Message);

export type LlmPromptsReadLlmPromptsData = {
    limit?: number;
    skip?: number;
};

export type LlmPromptsReadLlmPromptsResponse = (LLMPromptsPublic);

export type LlmPromptsCreateLlmPromptData = {
    requestBody: LLMPromptCreate;
};

export type LlmPromptsCreateLlmPromptResponse = (LLMPromptPublic);

export type LlmPromptsReadLlmPromptData = {
    id: number;
};

export type LlmPromptsReadLlmPromptResponse = (LLMPromptPublic);

export type LlmPromptsUpdateLlmPromptData = {
    id: number;
    requestBody: LLMPromptUpdate;
};

export type LlmPromptsUpdateLlmPromptResponse = (LLMPromptPublic);

export type LlmPromptsDeleteLlmPromptData = {
    id: number;
};

export type LlmPromptsDeleteLlmPromptResponse = (Message);

export type LlmPromptsTestLlmPromptData = {
    formData: Body_llm_prompts_test_llm_prompt;
    id: number;
};

export type LlmPromptsTestLlmPromptResponse = (LLMPromptTestResponse);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SourceConfigsReadSourceConfigsData = {
    limit?: number;
    skip?: number;
};

export type SourceConfigsReadSourceConfigsResponse = (SourceConfigsPublic);

export type SourceConfigsCreateSourceConfigData = {
    requestBody: SourceConfigCreate;
};

export type SourceConfigsCreateSourceConfigResponse = (SourceConfigPublic);

export type SourceConfigsReadSourceConfigData = {
    id: number;
};

export type SourceConfigsReadSourceConfigResponse = (SourceConfigPublic);

export type SourceConfigsUpdateSourceConfigData = {
    id: number;
    requestBody: SourceConfigUpdate;
};

export type SourceConfigsUpdateSourceConfigResponse = (SourceConfigPublic);

export type SourceConfigsDeleteSourceConfigData = {
    id: number;
};

export type SourceConfigsDeleteSourceConfigResponse = (Message);

export type SourceConfigsTestSourceConfigConnectionData = {
    id: number;
};

export type SourceConfigsTestSourceConfigConnectionResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);