// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Schema for creating a new source configuration.
 */
export type SourceConfigCreate = {
    /**
     * Data source type
     */
    type: SourceType;
    /**
     * User-defined name for this configuration
     */
    name: string;
    /**
     * Source-specific configuration
     */
    config_payload: {
        [key: string]: unknown;
    };
    /**
     * Whether this config is active
     */
    is_active?: boolean;
    user_id: string;
};

/**
 * Schema for source configuration returned from API.
 */
export type SourceConfigPublic = {
    /**
     * Data source type
     */
    type: SourceType;
    /**
     * User-defined name for this configuration
     */
    name: string;
    /**
     * Source-specific configuration
     */
    config_payload: {
        [key: string]: unknown;
    };
    /**
     * Whether this config is active
     */
    is_active?: boolean;
    id: number;
    user_id: string;
    created_at: string;
    updated_at: string;
};

/**
 * Schema for paginated list of source configurations.
 */
export type SourceConfigsPublic = {
    data: Array<SourceConfigPublic>;
    count: number;
};

/**
 * Schema for updating source configuration.
 */
export type SourceConfigUpdate = {
    name?: (string | null);
    config_payload?: ({
    [key: string]: unknown;
} | null);
    is_active?: (boolean | null);
};

/**
 * Data source types.
 */
export type SourceType = 'GIT' | 'DAYFLOW' | 'SIYUAN';

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SourceConfigsReadSourceConfigsData = {
    limit?: number;
    skip?: number;
};

export type SourceConfigsReadSourceConfigsResponse = (SourceConfigsPublic);

export type SourceConfigsCreateSourceConfigData = {
    requestBody: SourceConfigCreate;
};

export type SourceConfigsCreateSourceConfigResponse = (SourceConfigPublic);

export type SourceConfigsReadSourceConfigData = {
    id: number;
};

export type SourceConfigsReadSourceConfigResponse = (SourceConfigPublic);

export type SourceConfigsUpdateSourceConfigData = {
    id: number;
    requestBody: SourceConfigUpdate;
};

export type SourceConfigsUpdateSourceConfigResponse = (SourceConfigPublic);

export type SourceConfigsDeleteSourceConfigData = {
    id: number;
};

export type SourceConfigsDeleteSourceConfigResponse = (Message);

export type SourceConfigsTestSourceConfigConnectionData = {
    id: number;
};

export type SourceConfigsTestSourceConfigConnectionResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);