"""del emb field

Revision ID: a122ff0b2c49
Revises: a982006e4436
Create Date: 2026-01-10 03:10:11.137820

"""
import pgvector
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a122ff0b2c49'
down_revision = 'a982006e4436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_embedding', 'embedding')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_embedding', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
