"""init

Revision ID: 7c9c53883c9d
Revises: 
Create Date: 2026-01-03 02:08:41.796057

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = '7c9c53883c9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
                    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('owner_id', sa.Uuid(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_item_owner_id'), 'item', ['owner_id'], unique=False)
    op.create_table('user',
                    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_item_owner_id'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
