"""llm

Revision ID: f447575315ba
Revises: fe24ba25e5c3
Create Date: 2026-01-04 01:45:51.764426

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f447575315ba'
down_revision = 'fe24ba25e5c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_analysis',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('img_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('source_type', sa.Enum('SIYUAN_LOCAL', 'URL', name='imagesourcetype'), nullable=False),
                    sa.Column('llm_prompt_id', sa.Integer(), nullable=False),
                    sa.Column('analysis_result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=False),
                    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_image_analysis_img_path'), 'image_analysis', ['img_path'], unique=False)
    op.create_index(op.f('ix_image_analysis_llm_prompt_id'), 'image_analysis', ['llm_prompt_id'], unique=False)
    op.create_index(op.f('ix_image_analysis_source_type'), 'image_analysis', ['source_type'], unique=False)
    op.create_index(op.f('ix_image_analysis_status'), 'image_analysis', ['status'], unique=False)
    op.create_table('llm_model_config',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('provider', sa.Enum('OPENAI', 'ANTHROPIC', 'OLLAMA', name='llmprovider'), nullable=False),
                    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_llm_model_config_is_active'), 'llm_model_config', ['is_active'], unique=False)
    op.create_index(op.f('ix_llm_model_config_model_id'), 'llm_model_config', ['model_id'], unique=False)
    op.create_index(op.f('ix_llm_model_config_name'), 'llm_model_config', ['name'], unique=False)
    op.create_index(op.f('ix_llm_model_config_provider'), 'llm_model_config', ['provider'], unique=False)
    op.create_table('llm_prompt',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_llm_prompt_name'), 'llm_prompt', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_prompt_name'), table_name='llm_prompt')
    op.drop_table('llm_prompt')
    op.drop_index(op.f('ix_llm_model_config_provider'), table_name='llm_model_config')
    op.drop_index(op.f('ix_llm_model_config_name'), table_name='llm_model_config')
    op.drop_index(op.f('ix_llm_model_config_model_id'), table_name='llm_model_config')
    op.drop_index(op.f('ix_llm_model_config_is_active'), table_name='llm_model_config')
    op.drop_table('llm_model_config')
    op.drop_index(op.f('ix_image_analysis_status'), table_name='image_analysis')
    op.drop_index(op.f('ix_image_analysis_source_type'), table_name='image_analysis')
    op.drop_index(op.f('ix_image_analysis_llm_prompt_id'), table_name='image_analysis')
    op.drop_index(op.f('ix_image_analysis_img_path'), table_name='image_analysis')
    op.drop_table('image_analysis')
    # ### end Alembic commands ###
