"""activity embedding

Revision ID: a982006e4436
Revises: 485866665930
Create Date: 2026-01-10 02:00:47.682132

"""
import pgvector
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a982006e4436'
down_revision = '485866665930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('chunk_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedder_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedder_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_embedding_activity_id'), 'activity_embedding', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_embedding_user_id'), 'activity_embedding', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_embedding_user_id'), table_name='activity_embedding')
    op.drop_index(op.f('ix_activity_embedding_activity_id'), table_name='activity_embedding')
    op.drop_table('activity_embedding')
    # ### end Alembic commands ###
