"""vlm image analysis

Revision ID: 4048e1a2d6c1
Revises: fe24ba25e5c3
Create Date: 2026-01-04 01:16:26.047540

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = '4048e1a2d6c1'
down_revision = 'fe24ba25e5c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_analysis',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('img_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('source_type', sa.Enum('SIYUAN_LOCAL', 'URL', name='imagesourcetype'), nullable=False),
                    sa.Column('vlm_prompt_id', sa.Integer(), nullable=False),
                    sa.Column('analysis_result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=False),
                    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_image_analysis_img_path'), 'image_analysis', ['img_path'], unique=False)
    op.create_index(op.f('ix_image_analysis_source_type'), 'image_analysis', ['source_type'], unique=False)
    op.create_index(op.f('ix_image_analysis_status'), 'image_analysis', ['status'], unique=False)
    op.create_index(op.f('ix_image_analysis_vlm_prompt_id'), 'image_analysis', ['vlm_prompt_id'], unique=False)
    op.create_table('vlm_prompt',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_vlm_prompt_name'), 'vlm_prompt', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vlm_prompt_name'), table_name='vlm_prompt')
    op.drop_table('vlm_prompt')
    op.drop_index(op.f('ix_image_analysis_vlm_prompt_id'), table_name='image_analysis')
    op.drop_index(op.f('ix_image_analysis_status'), table_name='image_analysis')
    op.drop_index(op.f('ix_image_analysis_source_type'), table_name='image_analysis')
    op.drop_index(op.f('ix_image_analysis_img_path'), table_name='image_analysis')
    op.drop_table('image_analysis')
    # ### end Alembic commands ###
