"""add_activity source_config tables

Revision ID: fe24ba25e5c3
Revises: 7c9c53883c9d
Create Date: 2026-01-03 14:47:52.013972

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe24ba25e5c3'
down_revision = '7c9c53883c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_config_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.Enum('GIT', 'DAYFLOW', 'SIYUAN', name='sourcetype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_fingerprint'), 'activity', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_activity_source_config_id'), 'activity', ['source_config_id'], unique=False)
    op.create_index(op.f('ix_activity_source_type'), 'activity', ['source_type'], unique=False)
    op.create_index(op.f('ix_activity_user_id'), 'activity', ['user_id'], unique=False)
    op.create_table('source_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('GIT', 'DAYFLOW', 'SIYUAN', name='sourcetype'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_config_type'), 'source_config', ['type'], unique=False)
    op.create_index(op.f('ix_source_config_user_id'), 'source_config', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_config_user_id'), table_name='source_config')
    op.drop_index(op.f('ix_source_config_type'), table_name='source_config')
    op.drop_table('source_config')
    op.drop_index(op.f('ix_activity_user_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_source_type'), table_name='activity')
    op.drop_index(op.f('ix_activity_source_config_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_fingerprint'), table_name='activity')
    op.drop_table('activity')
    # ### end Alembic commands ###
