"""add 1024 vector

Revision ID: 435f60a3fffe
Revises: a122ff0b2c49
Create Date: 2026-01-10 03:10:55.520190

"""
import pgvector
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '435f60a3fffe'
down_revision = 'a122ff0b2c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_embedding', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_embedding', 'embedding')
    # ### end Alembic commands ###
