"""add extra_info

Revision ID: 485866665930
Revises: f447575315ba
Create Date: 2026-01-05 00:35:13.891168

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '485866665930'
down_revision = 'f447575315ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_analysis', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_analysis', 'extra_data')
    # ### end Alembic commands ###
