/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutLlmPromptsRouteImport } from './routes/_layout/llm-prompts'
import { Route as LayoutLlmModelsRouteImport } from './routes/_layout/llm-models'
import { Route as LayoutImageAnalysesRouteImport } from './routes/_layout/image-analyses'
import { Route as LayoutDatasourcesRouteImport } from './routes/_layout/datasources'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLlmPromptsRoute = LayoutLlmPromptsRouteImport.update({
  id: '/llm-prompts',
  path: '/llm-prompts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLlmModelsRoute = LayoutLlmModelsRouteImport.update({
  id: '/llm-models',
  path: '/llm-models',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutImageAnalysesRoute = LayoutImageAnalysesRouteImport.update({
  id: '/image-analyses',
  path: '/image-analyses',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDatasourcesRoute = LayoutDatasourcesRouteImport.update({
  id: '/datasources',
  path: '/datasources',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/datasources': typeof LayoutDatasourcesRoute
  '/image-analyses': typeof LayoutImageAnalysesRoute
  '/llm-models': typeof LayoutLlmModelsRoute
  '/llm-prompts': typeof LayoutLlmPromptsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/datasources': typeof LayoutDatasourcesRoute
  '/image-analyses': typeof LayoutImageAnalysesRoute
  '/llm-models': typeof LayoutLlmModelsRoute
  '/llm-prompts': typeof LayoutLlmPromptsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/datasources': typeof LayoutDatasourcesRoute
  '/_layout/image-analyses': typeof LayoutImageAnalysesRoute
  '/_layout/llm-models': typeof LayoutLlmModelsRoute
  '/_layout/llm-prompts': typeof LayoutLlmPromptsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/datasources'
    | '/image-analyses'
    | '/llm-models'
    | '/llm-prompts'
    | '/settings'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/datasources'
    | '/image-analyses'
    | '/llm-models'
    | '/llm-prompts'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/datasources'
    | '/_layout/image-analyses'
    | '/_layout/llm-models'
    | '/_layout/llm-prompts'
    | '/_layout/settings'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/llm-prompts': {
      id: '/_layout/llm-prompts'
      path: '/llm-prompts'
      fullPath: '/llm-prompts'
      preLoaderRoute: typeof LayoutLlmPromptsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/llm-models': {
      id: '/_layout/llm-models'
      path: '/llm-models'
      fullPath: '/llm-models'
      preLoaderRoute: typeof LayoutLlmModelsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/image-analyses': {
      id: '/_layout/image-analyses'
      path: '/image-analyses'
      fullPath: '/image-analyses'
      preLoaderRoute: typeof LayoutImageAnalysesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/datasources': {
      id: '/_layout/datasources'
      path: '/datasources'
      fullPath: '/datasources'
      preLoaderRoute: typeof LayoutDatasourcesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutDatasourcesRoute: typeof LayoutDatasourcesRoute
  LayoutImageAnalysesRoute: typeof LayoutImageAnalysesRoute
  LayoutLlmModelsRoute: typeof LayoutLlmModelsRoute
  LayoutLlmPromptsRoute: typeof LayoutLlmPromptsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutDatasourcesRoute: LayoutDatasourcesRoute,
  LayoutImageAnalysesRoute: LayoutImageAnalysesRoute,
  LayoutLlmModelsRoute: LayoutLlmModelsRoute,
  LayoutLlmPromptsRoute: LayoutLlmPromptsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
